name:                chat-server-haskell
version:             0.1.0.0
github:              "mherrera01/chat-server-haskell"
license:             BSD3
author:              "Miguel Herrera"
maintainer:          "miguelherrera8600@gmail.com"
copyright:           "Copyright (c) 2022 Miguel Herrera"

extra-source-files:
- README.md
- ChangeLog.md

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mherrera01/chat-server-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- yesod
- yesod-static
- yesod-form
- text
- data-default
- containers
- async
- directory
- stm
- shakespeare
- aeson
- yaml
- file-embed

library:
  source-dirs: src

executables:
  chat-server-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chat-server-haskell

tests:
  chat-server-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chat-server-haskell
